name: sleep_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^4.17.2
  equatable: ^2.0.5
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  geolocator: ^11.0.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.1
  intl: ^0.18.1
  local_auth: ^2.2.0
  progress_line: ^0.1.0
  shadcn_ui: ^0.4.3
  url_launcher: ^6.2.6
  weather: ^3.1.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
